### ISSUE TITLE
Epic: CUDA/GPU wishlist

### ISSUE THREAD

**Issue by johnlees** [mrc-ide/dust#186]
- [ ] Compiled particle filter
- - [ ] Store data on device, make compare a device function
- - [ ] Make a CUDA version of weights using reductions
- - [ ] Make a CUDA version of history saving using index
- [ ] Better handling of pars when one particle per pars (should probably interleave them)
- [ ] Set up build kite for running tests #78 
- [ ] Break up dust object #154 
- [ ] Add numeric limits helper #165
